# Security routes
security_controllers:
    resource: ../src/Controller/SecurityController.php
    type: attribute

# Admin routes
admin_controllers:
    resource: ../src/Controller/Admin/
    type: attribute

# UserManagement routes
user_management_controllers:
    resource: ../src/Module/UserManagement/Controller/
    type: attribute

# ExercisesQuizzes routes
exercises_quizzes_controllers:
    resource: ../src/Module/ExercisesQuizzes/Controller/
    type: attribute

# Forum routes
forum_controllers:
    resource: ../src/Module/Forum/Controller/
    type: attribute

# InternationalTests routes
international_tests_controllers:
    resource: ../src/Module/InternationalTests/Controller/
    type: attribute

# PedagogicalContent routes
pedagogical_content_controllers:
    resource: ../src/Module/PedagogicalContent/Controller/
    type: attribute

# Support routes
support_controllers:
    resource: ../src/Module/Support/Controller/
    type: attribute
